### ISSUE TITLE
Datasets 'voc_2007_trainval_base1' is not registered！

### ISSUE THREAD

**Issue by Biubiubiu12** [ucbdrive/few-shot-object-detection#139] opened 2021-10-19 07:04 UTC
Hello, thank you very much for your project. I had some problems invoking the dataset during training. 
First, I downloaded the VOC dataset.
VOC20{07,12}/
  Annotations/
  ImageSets/
  JPEGImages/
and I also  generatesd  seeds,but there was no .txt file. 
vocsplit/
  seed{1-29}/
    # shots
Then I want to train, but show ‘VOC_ 2007_ traincal_ Base1’ is not registered. I want to ask about this VOC_ xx_ trainval_ Base need to run any additional programs before training?
-----------------My environment is installed offline. I don't know if it also has an impact on this.

**Comment by thomasehuang** [comment] 2021-10-23 23:51
Closing this as it is a duplicate of #140.

**Closed as completed by thomasehuang** 2021-10-23 23:51 UTC
